application: cointrader-1072
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /favicon\.ico
  static_files: pics/favicon.ico
  upload: pics/favicon\.ico

- url: /pics
  static_dir: pics

- url: /fonts
  static_dir: fonts

- url: /files
  static_dir: files


- url: /.*
  script: coin-trader.app
